# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f23033ceebb0461f11ca951b716703c3788b33d353aff9a93592d6f6a0ffe0b98ec9444c40ccb5cdc90d961130c7cc9cacda7ea3719190490ca3c63b9df2e879

test:
  secret_key_base: 16bbdea3eae98ba9a66831d90c88bb40be6baeaa9d57d30a26698ae916651d6beed0f1013d5d4fecc2953c0dea6906a5ccdaf93e2140f1514e685c302ee286c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
